# -*- coding: utf-8 -*-
"""cryptocurrency tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-d9-5LeZi7nqongL0eiO27ufJCQpdIJc
"""

pip install requests

import requests
import time

def get_crypto_price(crypto_id="bitcoin", currency="usd"):
    url = f"https://api.coingecko.com/api/v3/simple/price?ids={crypto_id}&vs_currencies={currency}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        return data[crypto_id][currency]
    else:
        print("Error fetching data from CoinGecko API.")
        return None

# Track prices in a loop
def track_price(crypto_id="bitcoin", currency="usd", interval=60):
    while True:
        price = get_crypto_price(crypto_id, currency)
        if price is not None:
            print(f"The current price of {crypto_id.capitalize()} in {currency.upper()} is: {price}")
        else:
            print("Failed to retrieve price.")
        time.sleep(interval)  # Wait for specified interval before fetching price again

# Customize with your preferred cryptocurrency and interval in seconds
crypto_id = input("Enter cryptocurrency ID (e.g., bitcoin, ethereum): ").strip().lower()
currency = input("Enter target currency (e.g., usd, eur): ").strip().lower()
interval = int(input("Enter update interval in seconds (e.g., 60): "))

track_price(crypto_id, currency, interval)